// <auto-generated />
namespace farmers_land.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedsomeextrafieldsrequiredforausertologin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedsomeextrafieldsrequiredforausertologin));
        
        string IMigrationMetadata.Id
        {
            get { return "201804201453557_Added some extra fields required for a user to log in"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
